version: 2.1
jobs:
  compile:
   docker:
      - image: archlinux:base-devel
   resource_class: large
   steps:
      - run:
          command: |
           pacman -Syu --needed --noconfirm pacman-key --init  wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python3 python zip xxd
           git clone https://github.com/pocongtobat00/mark_project.git --depth 1 .
           git config --global user.name "pocongtobat00"
           git config --global user.email "pocongtobat00@gmail.com"
           git config --global color.ui false
           curl -fsSL "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" | bsdtar -C / -xvf -
           bash build
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
